// Auto-generated by setup-templates.mjs — do not edit manually
// Re-run `node functions/setup-templates.mjs` to refresh

export const BREVO_TEMPLATE_IDS = {
  bookingConfirmed:  4,
  bookingCancelled:  5,
  bookingCompleted:  6,
  invoiceSent:       7,
  paymentReceipt:    8,
  newBookingOwner:   9,
} as const

export type BrevoTemplateKey = keyof typeof BREVO_TEMPLATE_IDS
