import * as functions from 'firebase-functions'
import * as admin from 'firebase-admin'

const db = admin.firestore()

export const generateInvoice = functions.firestore
  .document('businesses/{businessId}/bookings/{bookingId}')
  .onUpdate(async (change, context) => {
    const before = change.before.data()
    const after  = change.after.data()
    const { businessId, bookingId } = context.params

    // Trigger invoice generation when booking is completed and payment status changes to paid
    if (before.paymentStatus !== 'paid' && after.paymentStatus === 'paid') {
      const invoiceRef = db.collection(`businesses/${businessId}/invoices`).doc()

      await invoiceRef.set({
        bookingId,
        customerName:  after.customerName,
        customerEmail: after.customerEmail,
        amount:        after.amount,
        tax:           after.amount * 0.1, // 10% tax
        total:         after.amount * 1.1,
        status:        'paid',
        pdfUrl:        null, // Generated by Cloud Storage trigger
        dueDate:       new Date().toISOString().split('T')[0],
        createdAt:     admin.firestore.FieldValue.serverTimestamp(),
        items: [{
          description: after.serviceName || 'Service',
          quantity:    1,
          unitPrice:   after.amount,
          total:       after.amount,
        }],
      })

      functions.logger.info(`Invoice generated for booking ${bookingId}`)
    }
  })
